#!/usr/bin/env bash
# File: 1-list_your_processes
# Description: List all processes for all users, in a user-friendly, hierarchical format
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest
