#!/usr/bin/env bash
# File: 1-list_your_processes
# Description: List all processes for all users (even without TTY),
# display user-oriented format, and show hierarchy, including PPID, TIME, and COMMAND.

ps ax --forest -o ppid=,time=,cmd=
