#!/usr/bin/env bash
# File: processes_and_signals/5-dont_stop_me_now
# Description: Stops any running instance(s) of 4-to_infinity_and_beyond using kill

# Find all PIDs matching the script name
mapfile -t pids < <(pgrep -f "4-to_infinity_and_beyond")

if (( ${#pids[@]} )); then
  for pid in "${pids[@]}"; do
    kill "$pid"  # Sends SIGTERM
  done
fi
