#!/bin/bash

# Start the target process in the background
./4-to_infinity_and_beyond &
TARGET_PID=$!

# Define a trap to handle SIGINT (Ctrl+C)
trap "echo 'Terminated'; kill $TARGET_PID" SIGINT

# Wait for the target process to finish
wait $TARGET_PID

